/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:83b699e8-ca4f-4a44-8a44-e962b98a89c0",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_t49PY89oB",
    "aws_user_pools_web_client_id": "4mb7b1pm3anhqvml1bmm5dte7k",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ltyn3lzhw5dinp2f2ao5mm74v4.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
